Make sure that return_bytes function returns int value
php_admin_value[post_max_size] in PHP fpm pool config set to big integer
(i.e. 106954752) causes fb-client to crash if file is bigger than
10485760 bytes with traceback

Traceback (most recent call last):
[...]
 File "/usr/bin/fb", line 138, in upload_files
    if self.serverConfig is not None and (currentChunkSize + filesize > self.serverConfig["request_max_size"] \
TypeError: unorderable types: int() > str()

because api/v2.1.0/file/get_config returns "request_max_size" as string

Changes by Florian Pritz:
 - Add test
 - Add github PR body as commit message
 - Split off indentation change

Signed-off-by: Florian Pritz <bluewind@xinu.at>